export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export type INCREMENT_COUNTER = typeof INCREMENT_COUNTER;

export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export type DECREMENT_COUNTER = typeof DECREMENT_COUNTER;

export const FETCH_MAXIMUM = 'FETCH_MAXIMUM';
export type FETCH_MAXIMUM = typeof FETCH_MAXIMUM;

export const FETCH_MAXIMUM_SUCCESS = 'FETCH_MAXIMUM_SUCCESS';
export type FETCH_MAXIMUM_SUCCESS = typeof FETCH_MAXIMUM_SUCCESS;

export const FETCH_MAXIMUM_FAILURE = 'FETCH_MAXIMUM_FAILURE';
export type FETCH_MAXIMUM_FAILURE = typeof FETCH_MAXIMUM_FAILURE;

export const EXPIRE_COUNTER = 'EXPIRE_COUNTER';
export type EXPIRE_COUNTER = typeof EXPIRE_COUNTER;

export const CANCELL_COUNTER = 'CANCELL_COUNTER';
export type CANCELL_COUNTER = typeof CANCELL_COUNTER;

export const COMPLETE_COUNTER = 'COMPLETE_COUNTER';
export type COMPLETE_COUNTER = typeof COMPLETE_COUNTER;
