export const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED';
export type COUNTDOWN_TERMINATED = typeof COUNTDOWN_TERMINATED;

export const START_COUNTDOWN = 'START_COUNTDOWN';
export type START_COUNTDOWN = typeof START_COUNTDOWN;

export const DECREMENT_COUNTDOWN = 'DECREMENT_COUNTDOWN';
export type DECREMENT_COUNTDOWN = typeof DECREMENT_COUNTDOWN;
